---
- name: Install
  become: yes
  apt:
    name: nginx
    state: latest

- name: Start
  become: yes
  service: name=nginx state=started enabled=true

- name: Supprimer default.conf
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: PHP
  become: yes
  include: php.yml

- name: Site configuration
  become: yes
  include: site.yml
  with_items: domains
