---
 - name: Add dotDeb deposit
   apt_repository: repo='{{ item}}'  
   with_items:
      - deb http://packages.dotdeb.org jessie all
      - deb-src http://packages.dotdeb.org jessie all

 - name: Add key dotdeb
   apt_key: url=https://www.dotdeb.org/dotdeb.gpg

 - name: APT update
   apt: update_cache=yes

 - name: Install PHP
   apt: name={{ item }} state=latest
   with_items: php_packages

# - name: bad fonctions revocation 
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='disable_functions[\s]?=' line='disable_functions' - exec,passthru,shell_exec,proc_open,popen'
  
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size - {{ php_post_max_size }}
 
 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='memory_limit[\s]?=' line='memory_limit ={{ php_memory_limit}}'

 - lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='date.timezone[\s]?=' line='date.timezone{{php_timezone}}'
   notify: php restart
