---
 - name: Installation web
   hosts: web
   remote_user: bob
   vars:
     user: volibaer
     domains: 
        - local.dev
        - demo.fr

   roles: 
     - user
     - utils
     - nginx
   
        
...
