---
 - name: Installation web
   hosts: web
   remote_user: bob
   vars:
     user: volibaer
     domains: 
        - domain: local.dev
          php: no
          repo: https://github.com/Grafikart.github.io.git
        - domain: demo.fr
          php: yes

   roles: 
     - user
     - utils
     - nginx
   
        
...
